### ISSUE TITLE
XGBoostClassifier to PMML failed

### ISSUE THREAD

**Issue by leemoor** [jpmml/jpmml-sparkml-xgboost#10]
- hi vr, model here:

```

 val XGBooster = new XGBoostClassifier(
      Map("eta" -> 0.05f,
        "max_depth" -> 8,
        "objective" -> "binary:logistic",
        "eval_metric" -> "auc",
        "baseScore" -> 0.6,
        "maxBin" -> 16,
        "num_round" -> 5,   //500!!!!!
        "num_workers" -> 100
      )
    ).setFeaturesCol("features").setLabelCol("label")

    val pipeline = new Pipeline().setStages(Array(featureAssembler, XGBooster))
    val xgbmodel = pipeline.fit(train)

```

1. : using the README
    val pmmlBytes = ConverterUtil.toPMMLByteArray(train.schema, xgbmodel)

```
scala>     val pmmlBytes = ConverterUtil.toPMMLByteArray(train.schema, xgbmodel)
java.lang.UnsupportedOperationException: Replace "org.jpmml.sparkml.ConverterUtil.toPMMLByteArray(schema, pipelineModel)" with "new org.jpmml.sparkml.PMMLBuilder(schema, pipelineModel).buildByteArray()"
  at org.jpmml.sparkml.ConverterUtil.toPMMLByteArray(ConverterUtil.java:51)
  at org.jpmml.sparkml.ConverterUtil.toPMMLByteArray(ConverterUtil.java:46)
  ... 75 elided
```

2.   from above,change:
  val pmml = new PMMLBuilder(train.schema, xgbmodel).buildByteArray()

```
 scala>     val pmml = new PMMLBuilder(train.schema, xgbmodel).buildByteArray()
java.lang.IllegalArgumentException: Transformer class ml.dmlc.xgboost4j.scala.spark.XGBoostClassificationModel is not supported
  at org.jpmml.sparkml.ConverterFactory.newConverter(ConverterFactory.java:58)
  at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:105)
  at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:249)
  at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:245)
  ... 75 elided

```
confusing.....

**Comment by nithinsingh61** [comment]
Any updates on this issue? @leemoor did you find a workaround?
