### ISSUE TITLE
Exception in thread "main" java.lang.InstantiationError: org.dmg.pmml.tree.Node

### ISSUE THREAD

**Issue by haixiaoxuan** [jpmml/jpmml-sparkml-xgboost#12]
I want to save the pipeline model trained by xgboost4j-spark as PMML by using jpmml-sparkml-xgboost, and report the following error, may I ask why

```
Exception in thread "main" java.lang.InstantiationError: org.dmg.pmml.tree.Node
	at org.jpmml.xgboost.RegTree.encodeTreeModel(RegTree.java:92)
	at org.jpmml.xgboost.ObjFunction.createMiningModel(ObjFunction.java:68)
	at org.jpmml.xgboost.MultinomialLogisticRegression.encodeMiningModel(MultinomialLogisticRegression.java:55)
	at org.jpmml.xgboost.GBTree.encodeMiningModel(GBTree.java:77)
	at org.jpmml.xgboost.Learner.encodeMiningModel(Learner.java:151)
	at org.jpmml.sparkml.xgboost.BoosterUtil.encodeBooster(BoosterUtil.java:67)
	at org.jpmml.sparkml.xgboost.XGBoostClassificationModelConverter.encodeModel(XGBoostClassificationModelConverter.java:22)
	at org.jpmml.sparkml.xgboost.XGBoostClassificationModelConverter.encodeModel(XGBoostClassificationModelConverter.java:10)
	at org.jpmml.sparkml.ModelConverter.registerModel(ModelConverter.java:172)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:116)
	at example.XGboostTest$.main(XGboostTest.scala:106)
	at example.XGboostTest.main(XGboostTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:892)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by vruusmann** [comment]
> may I ask why

Mismatching dependency versions.

**Comment by haixiaoxuan** [comment]
@vruusmann 
Thank you for your answer
The versions of the components I used are as follows:
The spark 2.3.0
JPMML - xgboost 1.3.3
Xgboost4j - spark 0.81
JPMML - sparkml 1.4 x
You can tell me exactly which version of the component might have a problem
Thank you very much

**Comment by vruusmann** [comment]
> You can tell me exactly which version of the component might have a problem

Hard for me two know, because you don't even know your versions yourself (eg. "JPMML-SparkML 1.4.X").

A good rule of thumb is to use "latest everything". Today (9th of July, 2019), this combination would be:
- Spark 2.3.0
- JPMML-SparkML 1.4.11
- JPMML-XGBoost 1.3.11

**Comment by haixiaoxuan** [comment]
@vruusmann 
Thank you. According to your answer, this problem has been successfully solved.
