### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by fooSynaptic** [jpmml/jpmml-sparkml-xgboost#14]
hi, i tried to compile with this rep but this error:

```
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 h
[INFO] Finished at: 2020-01-19T12:30:21+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jpmml-sparkml-xgboost: Could not resolve dependencies for project org.jpmml:jpmml-sparkml-xgboost:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: ml.dmlc:xgboost4j-spark:jar:0.72, ml.dmlc:xgboost4j:jar:0.72, com.typesafe.akka:akka-actor_2.11:jar:2.3.11, org.scala-lang:scala-compiler:jar:2.11.8: Could not transfer artifact ml.dmlc:xgboost4j-spark:jar:0.72 from/to central (https://repo.maven.apache.org/maven2): GET request of: ml/dmlc/xgboost4j-spark/0.72/xgboost4j-spark-0.72.jar from central failed: Read timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

the error seems the dependency resolve problem, i add following dependency in pom.xml
```
<dependency>
  <groupId>ml.dmlc</groupId>
  <artifactId>xgboost4j-spark</artifactId>
  <version>latest_version_num</version>
</dependency>
```

but still got this error:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/mvnpackages/jpmml-sparkml-xgboost/src/main/java/org/jpmml/sparkml/xgboost/HasXGBoostOptions.java:[21,25] 找不到符号
  符号:   类 HasOptions
  位置: 程序包 org.jpmml.sparkml
[ERROR] /Users/mvnpackages/jpmml-sparkml-xgboost/src/main/java/org/jpmml/sparkml/xgboost/HasXGBoostOptions.java:[23,44] 找不到符号
  符号: 类 HasOptions
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.680 s
[INFO] Finished at: 2020-01-19T13:26:29+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project jpmml-sparkml-xgboost: Compilation failure: Compilation failure: 
[ERROR] /Users/mvnpackages/jpmml-sparkml-xgboost/src/main/java/org/jpmml/sparkml/xgboost/HasXGBoostOptions.java:[21,25] 找不到符号
[ERROR]   符号:   类 HasOptions
[ERROR]   位置: 程序包 org.jpmml.sparkml
[ERROR] /Users/mvnpackages/jpmml-sparkml-xgboost/src/main/java/org/jpmml/sparkml/xgboost/HasXGBoostOptions.java:[23,44] 找不到符号
[ERROR]   符号: 类 HasOptions
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
How to fix this?

**Comment by fooSynaptic** [comment]
i download the pre-compiled jar package from maven2(version`1.1.1`) but fail to run the readme example, the exception shows:
```
val pmmlBytes = ConverterUtil.toPMMLByteArray(df.schema, pipelineModel)

<console>:33: error: value toPMMLByteArray is not a member of object org.jpmml.sparkml.ConverterUtil

val pmmlBytes = new PMMLBuilder(df.schema, pipelineModel).buildByteArray()
java.lang.NoClassDefFoundError: com/sun/xml/bind/Locatable
  at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by fooSynaptic** [comment]
include `sun.xml.bind.jxbcore` fix this, but another error raise
```
scala> ConverterUtil.toPMML(df.schema, pipelineModel)
java.lang.NoClassDefFoundError: org/dmg/pmml/mining/MiningModel
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: org.dmg.pmml.mining.MiningModel
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 49 more
```

**Comment by fooSynaptic** [comment]
i got a bit understand that this rep extend the spark-ml and xgboost package

in your src code 
-  `error: object mining is not a member of package org.dmg.pmml`
- `error: object HasOptions is not a member of package org.jpmml.sparkml`
