### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by 1060905996** [jpmml/jpmml-sparkml-xgboost#16]
```
Exception in thread "main" java.lang.IllegalArgumentException: Transformer class ml.dmlc.xgboost4j.scala.spark.XGBoostRegressionModel is not supported
	at org.jpmml.sparkml.ConverterFactory.newConverter(ConverterFactory.java:58)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:105)
	at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:248)
	at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:244)
	at com.pactera.scala.MyXgBx$.main(MyXgBx.scala:37)
```

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: Transformer class ml.dmlc.xgboost4j.scala.spark.XGBoostRegressionModel is not supported

Fix your classpath - the JPMML-SparkML-XGBoost library seems to be missing from your Apache Spark application's classpath.

It's all explained in the README file.
