### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: ml.dmlc.xgboost4j.scala.ObjectiveTrait

### ISSUE THREAD

**Issue by Berwin77** [jpmml/jpmml-sparkml-xgboost#18]
i want use xgboost generate pmml   in IDEA.

env:

spark 2.3.3
xgboost-spark-0.90
pmml-evaluator 1.5.15
jpmml-xgboost 1.3.15
jpmml-sparkml 1.4.18

i have read the other same question, [the same question](https://github.com/dmlc/xgboost/issues/4666) ,but i have added xgboost-spark-0.90 in my maven lib.

```
var mlmodel = new XGBoostClassifier(Map("eta" -> 0.05f,
        "max_depth" -> 8,
        "objective" -> "binary:logistic",
        "eval_metric" -> "auc",
        "baseScore" -> 0.6,
        "maxBin" -> 16,
        "num_round" -> 5,   //500!!!!!
        "num_workers" -> 100
      )).setFeaturesCol("features").setLabelCol("label")
mlmodel = mlmodel.set(mlmodel.numRound, 11)
```
Run get error

```
Exception in thread "main" java.lang.NoClassDefFoundError: ml/dmlc/xgboost4j/scala/ObjectiveTrait
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at org.apache.spark.ml.param.Params$class.params(params.scala:675)
	at org.apache.spark.ml.PipelineStage.params$lzycompute(Pipeline.scala:42)
	at org.apache.spark.ml.PipelineStage.params(Pipeline.scala:42)
	at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:254)
	at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$$anonfun$XGBoostToMLlibParams$2.apply(GeneralParams.scala:245)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.xgboost4j.scala.spark.params.ParamMapFuncs$class.XGBoostToMLlibParams(GeneralParams.scala:245)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.XGBoostToMLlibParams(XGBoostClassifier.scala:44)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:57)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:54)
	at OnlineService.spark.ModelBuild$.getProcessTransformer(ModelBuild.scala:68)
	at OnlineService.spark.Model2PMML$.run(Model2PMML.scala:136)
	at OnlineService.spark.Model2PMML$.main(Model2PMML.scala:25)
	at OnlineService.spark.Model2PMML.main(Model2PMML.scala)
Caused by: java.lang.ClassNotFoundException: ml.dmlc.xgboost4j.scala.ObjectiveTrait
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

```

hope your reply, thank you very much.

**Comment by vruusmann** [comment]
This exception is not related to the JPMML-SparkML-Library in any way - the stack trace doesn't contain any mentions of `org.jpmml` classes.

If you need help setting up XGBoost4J in Apache Spark ML environment, then you should post your question to Stackoverflow.

**Comment by vruusmann** [comment]
My intuition is that you're trying to use an outdated `xgboost-spark` library version.

**Comment by Berwin77** [comment]
thank you very much, Brother!  your guess direction is true. I am very stupied. I read [xgboost-spark jars maven describe](https://mvnrepository.com/artifact/ml.dmlc/xgboost4j-spark/0.90) again. i find i don't add corresponding xgboost4j jar to xgboost-spark. when i add dependency in my project.  it work finally.  that is very exciting.   thanks brother again!!
